language: java
sudo: false
services:
  - docker

before_script:
  - docker run --name blood_donation -e POSTGRES_USER=$JDBC_DATABASE_USERNAME -e POSTGRES_DB=blood_donation -e POSTGRES_PASSWORD=$JDBC_DATABASE_PASSWORD -p 5432:5432 -d postgres

deploy:
    provider: heroku
    api_key: $HEROKU_API_KEY
    app:
      production: machava-backend
      staging: machava-backend-staging
      development: machava-backend-dev
