spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}

  liquibase:
    change-log: classpath:/changelogs/changelog-master.yaml

management:
  endpoints:
    web:
      exposure:
        include: "*"

request:
  logging:
    shouldLog: false # log REST API calls

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG # log sql query
        type:
          descriptor:
            sql:
              BasicBinder: TRACE # log sql parameters
